spring:
  profiles:
    active:
      -  dog 
      -  EN
      -  prod
guru:
  username: SuperUsername
  password: dbPassword
  jdbcurl: SomeUrlforDB

---

spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl